id: P3307419E
initial_creation_type: ocr
source_metadata:
  volumes:
    1227dc9acde24002aae4bbea1259159d:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: རབ་ཏུ་བྱེད་པ་ལག་པའི་ཚད་ཀྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
